export default {
  NAME: {
    SERVER_START: "SERVER_START",
    VALIDATION: "VALIDATION",
    ROUTER: "ROUTER",
    ERROR_MIDDLEWARE: "ERROR_MIDDLEWARE",
    API_KEY: "API_KEY",
    AUTHENTICATION: "AUTHENTICATION",
    SERVICE: "SERVICE"
  },
  SERVER_START: {
    FAILED: "SERVER_START.FAILED"
  },
  ERROR_MIDDLEWARE: {
    FAILED_TO_SEND_REPLY: "ERROR_MIDDLEWARE.FAILED_TO_SEND_REPLY"
  },
  API_KEY: {
    BAD_KEY: "API_KEY.BAD_KEY"
  },
  AUTHENTICATION: {
    UNAUTHORIZED: "AUTHENTICATION.UNAUTHORIZED"
  },
  SERVICE: {
    LOGIN: "SERVICE.LOGIN"
  }
};
